import TollFineEventModel from '../models/toll-fine-event.model.js';
import AutoGeneratedChargeModel from '../models/auto-generated-charge.model.js';

class TollFineService {
  async importFromCsv(rows, tenantId, userId) {
    const batchId = `BATCH-${Date.now()}`;
    const results = { imported: 0, matched: 0, unmatched: 0, errors: [] };

    for (const row of rows) {
      try {
        const event = await TollFineEventModel.create({
          tenant_id: tenantId,
          plate_number: row.plate_number,
          event_type: row.event_type || 'salik',
          event_timestamp: row.event_timestamp,
          amount: parseFloat(row.amount),
          location: row.location,
          source_reference: row.source_reference,
          import_batch_id: batchId,
        });
        results.imported++;

        const attributed = await this.attributeEvent(event.id, tenantId);
        if (attributed) results.matched++;
        else results.unmatched++;
      } catch (err) {
        results.errors.push({ row, error: err.message });
      }
    }

    return results;
  }

  async attributeEvent(eventId, tenantId) {
    const event = await TollFineEventModel.findById(eventId, tenantId);
    if (!event) return false;

    const match = await TollFineEventModel.findMatchingAgreement(
      event.plate_number, event.event_timestamp, tenantId
    );

    if (match) {
      const charge = await AutoGeneratedChargeModel.create({
        tenant_id: tenantId,
        agreement_id: match.agreement_id,
        charge_type: event.event_type === 'salik' ? 'EXTRA_KM' : 'LATE_FEE',
        calculation_basis: {
          toll_fine_event_id: event.id,
          event_type: event.event_type,
          plate_number: event.plate_number,
          event_timestamp: event.event_timestamp,
          location: event.location,
        },
        amount: parseFloat(event.amount),
        rule_reference: 'TOLL_FINE_ATTRIBUTION',
        rule_version: 'AUTO',
        approval_status: 'AUTO_APPROVED',
        approved_by_user_id: null,
        approved_at: null,
      });

      await TollFineEventModel.updateAttribution(eventId, tenantId, match.agreement_id, charge.id, 'matched');
      return true;
    }

    await TollFineEventModel.updateAttribution(eventId, tenantId, null, null, 'unmatched');
    return false;
  }

  async manualAttribute(eventId, agreementId, tenantId, userId) {
    const event = await TollFineEventModel.findById(eventId, tenantId);
    if (!event) throw Object.assign(new Error('Event not found'), { statusCode: 404 });

    const charge = await AutoGeneratedChargeModel.create({
      tenant_id: tenantId,
      agreement_id: agreementId,
      charge_type: event.event_type === 'salik' ? 'EXTRA_KM' : 'LATE_FEE',
      calculation_basis: {
        toll_fine_event_id: event.id, event_type: event.event_type,
        plate_number: event.plate_number, manual_attribution: true,
      },
      amount: parseFloat(event.amount),
      rule_reference: 'TOLL_FINE_MANUAL', rule_version: 'MANUAL',
      approval_status: 'AUTO_APPROVED', approved_by_user_id: userId, approved_at: new Date(),
    });

    await TollFineEventModel.updateAttribution(eventId, tenantId, agreementId, charge.id, 'manual', userId);

    try {
      const AuditLogService = (await import('./audit-log.service.js')).default;
      await AuditLogService.logSystemEvent({
        tenantId, userId,
        action: 'toll_fine_manual_attribution', entityType: 'toll_fine_event', entityId: eventId,
        newValue: { agreement_id: agreementId, charge_id: charge.id, amount: event.amount },
      });
    } catch (e) { /* non-blocking */ }

    return { event: await TollFineEventModel.findById(eventId, tenantId), charge };
  }

  async getUnmatchedQueue(tenantId, filters = {}) {
    return TollFineEventModel.findUnmatched(tenantId, filters);
  }

  async reprocessPending(tenantId) {
    const pending = await TollFineEventModel.findUnmatched(tenantId);
    let matched = 0;
    for (const event of pending) {
      const result = await this.attributeEvent(event.id, tenantId);
      if (result) matched++;
    }
    return { total: pending.length, matched, remaining: pending.length - matched };
  }
}

export default new TollFineService();
