// Comprehensive list of countries / nationalities for dropdowns.
// UAE is placed first as the most common nationality for this market.
export const COUNTRIES: string[] = [
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'India',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Philippines',
  'Egypt',
  'Jordan',
  'Lebanon',
  'Syria',
  'Iraq',
  'Yemen',
  'Sudan',
  'Morocco',
  'Algeria',
  'Tunisia',
  'Libya',
  'United Kingdom',
  'United States',
  'Canada',
  'Australia',
  'New Zealand',
  'Ireland',
  'France',
  'Germany',
  'Italy',
  'Spain',
  'Portugal',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Russia',
  'Ukraine',
  'Romania',
  'Greece',
  'Turkey',
  'Iran',
  'Afghanistan',
  'China',
  'Japan',
  'South Korea',
  'Hong Kong',
  'Taiwan',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Myanmar',
  'Cambodia',
  'Kazakhstan',
  'Uzbekistan',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ethiopia',
  'Ghana',
  'Tanzania',
  'Uganda',
  'Somalia',
  'Brazil',
  'Argentina',
  'Mexico',
  'Colombia',
  'Chile',
  'Peru',
  'Venezuela',
  'Czech Republic',
  'Hungary',
  'Bulgaria',
  'Croatia',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Albania',
  'Azerbaijan',
  'Georgia',
  'Armenia',
  'Israel',
  'Palestine',
  'Mauritius',
  'Maldives',
  'Bhutan',
  'Other',
];
