import pool from '../config/database.js';

/**
 * AutoGeneratedCharge Model
 * Handles database operations for auto-generated charges
 */
class AutoGeneratedChargeModel {
  normalizeRuleVersion(ruleVersion) {
    if (!ruleVersion) return 'v1';
    return String(ruleVersion).slice(0, 20);
  }

  /**
   * Create auto-generated charge
   */
  async create(data) {
    const query = `
      INSERT INTO auto_generated_charges (
        tenant_id,
        agreement_id,
        charge_type,
        calculation_basis,
        amount,
        rule_reference,
        rule_version,
        approval_status,
        approved_by_user_id,
        approved_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      RETURNING *
    `;

    const values = [
      data.tenant_id,
      data.agreement_id,
      data.charge_type,
      JSON.stringify(data.calculation_basis),
      data.amount,
      data.rule_reference,
      this.normalizeRuleVersion(data.rule_version),
      data.approval_status,
      data.approved_by_user_id,
      data.approved_at,
    ];

    const result = await pool.query(query, values);
    return result.rows[0];
  }

  /**
   * Find charges by agreement ID
   */
  async findByAgreementId(agreementId, tenantId) {
    const query = `
      SELECT * FROM auto_generated_charges
      WHERE agreement_id = $1 AND tenant_id = $2
      ORDER BY generated_at ASC
    `;

    const result = await pool.query(query, [agreementId, tenantId]);
    return result.rows;
  }

  /**
   * Calculate total charges for agreement
   */
  async getTotalCharges(agreementId, tenantId) {
    const query = `
      SELECT SUM(amount) as total
      FROM auto_generated_charges
      WHERE agreement_id = $1 AND tenant_id = $2
        AND approval_status IN ('AUTO_APPROVED', 'APPROVED')
    `;

    const result = await pool.query(query, [agreementId, tenantId]);
    return parseFloat(result.rows[0].total || 0);
  }
}

export default new AutoGeneratedChargeModel();
